### ISSUE TITLE
Feature Request: clean homie device from MQTT 

### ISSUE THREAD

**Issue by stritti** [skoona/HomieMonitor#1]
Would be cool, if there would be a feature like this script within Homie Monitor:
https://gist.github.com/andreasgruener/9935ffecbc59404375e7a9cb4a9a8812

**Comment by skoona** [comment]
That would be easy enough today.  I'll start on it in late April.

**Comment by skoona** [comment]
Release 0.8.4 has the implemented and tested feature!  Thank you for the request.
