### ISSUE TITLE
Devices are not shown

### ISSUE THREAD

**Issue by kleini** [skoona/HomieMonitor#4]
and the following error message appears in the container logs

    homieMonitor    | 2019-05-28 20:29:26.792 HMIE:WARN  Services::Providers::Content#call Failure Request: Provider: Homie Monitor, klass=ArgumentError, cause=invalid byte sequence in UTF-8, Duration: 0.024 seconds, Backtrace=["/usr/local/lib/ruby/2.6.0/psych/visitors/yaml_tree.rb:298:in `visit_String'", "/usr/local/lib/ruby/2.6.0/psych/visitors/yaml_tree.rb:136:in `accept'"]

**Comment by kleini** [comment]
A restart of the container helps to resolve the issue.

**Comment by kleini** [comment]
Problem still happens. Here is a full stack trace

    homieMonitor    | #<Thread:0x000055650987f348@/vendor/bundle/ruby/2.6.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:471 run> terminated with exception (report_on_exception is true):
    homieMonitor    | Traceback (most recent call last):
    homieMonitor    | 	47: from /vendor/bundle/ruby/2.6.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
    homieMonitor    | 	46: from /mains/homie/providers/manager.rb:60:in `block in call'
    homieMonitor    | 	45: from /mains/homie/providers/manager.rb:60:in `loop'
    homieMonitor    | 	44: from /mains/homie/providers/manager.rb:62:in `block (2 levels) in call'
    homieMonitor    | 	43: from /mains/homie/providers/manager.rb:125:in `actions_router'
    homieMonitor    | 	42: from /mains/homie/providers/manager.rb:154:in `save_device_inventory'
    homieMonitor    | 	41: from /usr/local/lib/ruby/2.6.0/pstore.rb:335:in `transaction'
    homieMonitor    | 	40: from /usr/local/lib/ruby/2.6.0/pstore.rb:436:in `save_data'
    homieMonitor    | 	39: from /usr/local/lib/ruby/2.6.0/yaml/store.rb:64:in `dump'
    homieMonitor    | 	38: from /usr/local/lib/ruby/2.6.0/psych/core_ext.rb:13:in `to_yaml'
    homieMonitor    | 	37: from /usr/local/lib/ruby/2.6.0/psych.rb:513:in `dump'
    homieMonitor    | 	36: from /usr/local/lib/ruby/2.6.0/psych/visitors/yaml_tree.rb:118:in `push'
    homieMonitor    | 	35: from /usr/local/lib/ruby/2.6.0/psych/visitors/yaml_tree.rb:136:in `accept'
    homieMonitor    | 	34: from /usr/local/lib/ruby/2.6.0/psych/visitors/yaml_tree.rb:358:in `visit_Hash'
    homieMonitor    | 	33: from /usr/local/lib/ruby/2.6.0/psych/visitors/yaml_tree.rb:358:in `each'
    homieMonitor    | 	32: from /usr/local/lib/ruby/2.6.0/psych/visitors/yaml_tree.rb:360:in `block in visit_Hash'
    homieMonitor    | 	31: from /usr/local/lib/ruby/2.6.0/psych/visitors/yaml_tree.rb:136:in `accept'
    homieMonitor    | 	30: from /usr/local/lib/ruby/2.6.0/psych/visitors/yaml_tree.rb:381:in `visit_Array'
    homieMonitor    | 	29: from /usr/local/lib/ruby/2.6.0/psych/visitors/yaml_tree.rb:389:in `visit_Enumerator'
    homieMonitor    | 	28: from /usr/local/lib/ruby/2.6.0/psych/visitors/yaml_tree.rb:389:in `each'
    homieMonitor    | 	27: from /usr/local/lib/ruby/2.6.0/psych/visitors/yaml_tree.rb:389:in `block in visit_Enumerator'
    homieMonitor    | 	26: from /usr/local/lib/ruby/2.6.0/psych/visitors/yaml_tree.rb:136:in `accept'
    homieMonitor    | 	25: from /usr/local/lib/ruby/2.6.0/psych/visitors/yaml_tree.rb:163:in `visit_Object'
    homieMonitor    | 	24: from /usr/local/lib/ruby/2.6.0/psych/visitors/yaml_tree.rb:544:in `dump_ivars'
    homieMonitor    | 	23: from /usr/local/lib/ruby/2.6.0/psych/visitors/yaml_tree.rb:544:in `each'
    homieMonitor    | 	22: from /usr/local/lib/ruby/2.6.0/psych/visitors/yaml_tree.rb:546:in `block in dump_ivars'
    homieMonitor    | 	21: from /usr/local/lib/ruby/2.6.0/psych/visitors/yaml_tree.rb:136:in `accept'
    homieMonitor    | 	20: from /usr/local/lib/ruby/2.6.0/psych/visitors/yaml_tree.rb:381:in `visit_Array'
    homieMonitor    | 	19: from /usr/local/lib/ruby/2.6.0/psych/visitors/yaml_tree.rb:389:in `visit_Enumerator'
    homieMonitor    | 	18: from /usr/local/lib/ruby/2.6.0/psych/visitors/yaml_tree.rb:389:in `each'
homieMonitor    | 	17: from /usr/local/lib/ruby/2.6.0/psych/visitors/yaml_tree.rb:389:in `block in visit_Enumerator'
homieMonitor    | 	16: from /usr/local/lib/ruby/2.6.0/psych/visitors/yaml_tree.rb:136:in `accept'
homieMonitor    | 	15: from /usr/local/lib/ruby/2.6.0/psych/visitors/yaml_tree.rb:163:in `visit_Object'
homieMonitor    | 	14: from /usr/local/lib/ruby/2.6.0/psych/visitors/yaml_tree.rb:544:in `dump_ivars'
homieMonitor    | 	13: from /usr/local/lib/ruby/2.6.0/psych/visitors/yaml_tree.rb:544:in `each'
homieMonitor    | 	12: from /usr/local/lib/ruby/2.6.0/psych/visitors/yaml_tree.rb:546:in `block in dump_ivars'
homieMonitor    | 	11: from /usr/local/lib/ruby/2.6.0/psych/visitors/yaml_tree.rb:136:in `accept'
homieMonitor    | 	10: from /usr/local/lib/ruby/2.6.0/psych/visitors/yaml_tree.rb:381:in `visit_Array'
homieMonitor    | 	 9: from /usr/local/lib/ruby/2.6.0/psych/visitors/yaml_tree.rb:389:in `visit_Enumerator'
homieMonitor    | 	 8: from /usr/local/lib/ruby/2.6.0/psych/visitors/yaml_tree.rb:389:in `each'
homieMonitor    | 	 7: from /usr/local/lib/ruby/2.6.0/psych/visitors/yaml_tree.rb:389:in `block in visit_Enumerator'
homieMonitor    | 	 6: from /usr/local/lib/ruby/2.6.0/psych/visitors/yaml_tree.rb:136:in `accept'
homieMonitor    | 	 5: from /usr/local/lib/ruby/2.6.0/psych/visitors/yaml_tree.rb:163:in `visit_Object'
homieMonitor    | 	 4: from /usr/local/lib/ruby/2.6.0/psych/visitors/yaml_tree.rb:544:in `dump_ivars'
homieMonitor    | 	 3: from /usr/local/lib/ruby/2.6.0/psych/visitors/yaml_tree.rb:544:in `each'
homieMonitor    | 	 2: from /usr/local/lib/ruby/2.6.0/psych/visitors/yaml_tree.rb:546:in `block in dump_ivars'
homieMonitor    | 	 1: from /usr/local/lib/ruby/2.6.0/psych/visitors/yaml_tree.rb:136:in `accept'
homieMonitor    | /usr/local/lib/ruby/2.6.0/psych/visitors/yaml_tree.rb:298:in `visit_String': invalid byte sequence in UTF-8 (ArgumentError)

**Comment by skoona** [comment]
Is this a fresh installation or had it been running ok for you?

**Comment by kleini** [comment]
I am using the docker image https://hub.docker.com/r/skoona/homie-monitor and SSL for MQTT. I still have some Homie V2 devices and thought, that maybe those are the cause for the encoding problems.
Every time, when then problem occurs, I redeploy the docker container completely fresh with new volumes to solve the issue for me. But this always kills all settings and uploaded firmwares.

**Comment by skoona** [comment]
Marcus,

I apologize for the delay in responding, it is my personal goal to support this package and promote it’s use in the Homie Community. I am currently examining the info you sent describing the error.  I can see that some unknown charactor was picked up in the mqtt stream which broke the save discovered item function.  I have added an exception handler around that particular function to prevent it’s failure from taking out the whole app.

What is the likely source of this this unknown character!  I can think of two sources.  

I would look for in the #setFormat() and #setUnit() method calls that are a part of Homie library.  A non-utf8 value should never had made through MQTT, or the other layers of transport on the way to this save function.

The other possible source worth a look would be the Docker connection to the underlying filesystem.  Which I’m guess you don’t have in place.  What I mean is this.  The Docker Image internally expect and uses some disk space for storage of config, device inventory, and homie images.  Docker makes this space available to the app as a part of the Docker Image; or connects those declared volumes to the underlying filesystem directories.  When connected directly to the filesystem they are permanent, but you must configure Docker to provide that connection.  If you have not it is possible for the IN-IMAGE volume to fill up and cause corruption, producing this unknown value which appears to blowup the device inventor save function.

I’m working on the exception handler for saving device info to be better able to tolerate this kind of error.  You might want to investigate configuring Docker to use real disk for this docker application image; or at least increase their size allocation.

James,
I’ll message you when I do the update!

**Comment by kleini** [comment]
Then I have an idea, what may be the cause. I implemented some temperature sensors and those sent for the sensor unit the value `°C`. Maybe that degree character is transferred wrong. Does ESP8266 really use UTF-8 for character encoding? I doubt that and will have a closer look there.
Regarding the Docker container everything should be fine. I just mounted some directories into the container. This should not cause any character encoding issues and I clear the directories always before launching homieMonitor again. But I will have a closer look here, too.
Thanks for your hints!

**Comment by skoona** [comment]
Pushed an update this morning to GitHub and Docker.

Let me know if this helps your situation.

James,

**Comment by skoona** [comment]
This will take a bit to analyze, but first glance indicates it was trying to save your device inventory to  a file in your filesystem and failed badly.

**Comment by skoona** [comment]
Updated to survive this exception and not crash the program. However, the offending non-utf8 character will prevent the save from occurring.  It may however appear on the screen and therefore allow it's removal or change.

**Comment by kleini** [comment]
Thank you very much for your exception handling. Let's see, when the exception occurs again.

**Comment by kleini** [comment]
I can see now the following exception in the container logs. But there is still no indicator, what character and where is wrong. How can I find that and eliminate it?
```
#<Thread:0x0000564c8e5881e0@/vendor/bundle/ruby/2.6.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:471 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	47: from /vendor/bundle/ruby/2.6.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
	46: from /mains/homie/providers/manager.rb:60:in `block in call'
	45: from /mains/homie/providers/manager.rb:60:in `loop'
	44: from /mains/homie/providers/manager.rb:62:in `block (2 levels) in call'
	43: from /mains/homie/providers/manager.rb:125:in `router'
	42: from /mains/homie/providers/manager.rb:158:in `save_device_inventory'
	41: from /usr/local/lib/ruby/2.6.0/pstore.rb:335:in `transaction'
	40: from /usr/local/lib/ruby/2.6.0/pstore.rb:436:in `save_data'
	39: from /usr/local/lib/ruby/2.6.0/yaml/store.rb:64:in `dump'
	38: from /usr/local/lib/ruby/2.6.0/psych/core_ext.rb:13:in `to_yaml'
	37: from /usr/local/lib/ruby/2.6.0/psych.rb:513:in `dump'
	36: from /usr/local/lib/ruby/2.6.0/psych/visitors/yaml_tree.rb:118:in `push'
	35: from /usr/local/lib/ruby/2.6.0/psych/visitors/yaml_tree.rb:136:in `accept'
	34: from /usr/local/lib/ruby/2.6.0/psych/visitors/yaml_tree.rb:358:in `visit_Hash'
	33: from /usr/local/lib/ruby/2.6.0/psych/visitors/yaml_tree.rb:358:in `each'
	32: from /usr/local/lib/ruby/2.6.0/psych/visitors/yaml_tree.rb:360:in `block in visit_Hash'
	31: from /usr/local/lib/ruby/2.6.0/psych/visitors/yaml_tree.rb:136:in `accept'
	30: from /usr/local/lib/ruby/2.6.0/psych/visitors/yaml_tree.rb:381:in `visit_Array'
	29: from /usr/local/lib/ruby/2.6.0/psych/visitors/yaml_tree.rb:389:in `visit_Enumerator'
	28: from /usr/local/lib/ruby/2.6.0/psych/visitors/yaml_tree.rb:389:in `each'
	27: from /usr/local/lib/ruby/2.6.0/psych/visitors/yaml_tree.rb:389:in `block in visit_Enumerator'
	26: from /usr/local/lib/ruby/2.6.0/psych/visitors/yaml_tree.rb:136:in `accept'
	25: from /usr/local/lib/ruby/2.6.0/psych/visitors/yaml_tree.rb:163:in `visit_Object'
	24: from /usr/local/lib/ruby/2.6.0/psych/visitors/yaml_tree.rb:544:in `dump_ivars'
	23: from /usr/local/lib/ruby/2.6.0/psych/visitors/yaml_tree.rb:544:in `each'
	22: from /usr/local/lib/ruby/2.6.0/psych/visitors/yaml_tree.rb:546:in `block in dump_ivars'
	21: from /usr/local/lib/ruby/2.6.0/psych/visitors/yaml_tree.rb:136:in `accept'
	20: from /usr/local/lib/ruby/2.6.0/psych/visitors/yaml_tree.rb:381:in `visit_Array'
	19: from /usr/local/lib/ruby/2.6.0/psych/visitors/yaml_tree.rb:389:in `visit_Enumerator'
	18: from /usr/local/lib/ruby/2.6.0/psych/visitors/yaml_tree.rb:389:in `each'
	17: from /usr/local/lib/ruby/2.6.0/psych/visitors/yaml_tree.rb:389:in `block in visit_Enumerator'
	16: from /usr/local/lib/ruby/2.6.0/psych/visitors/yaml_tree.rb:136:in `accept'
	15: from /usr/local/lib/ruby/2.6.0/psych/visitors/yaml_tree.rb:163:in `visit_Object'
	14: from /usr/local/lib/ruby/2.6.0/psych/visitors/yaml_tree.rb:544:in `dump_ivars'
	13: from /usr/local/lib/ruby/2.6.0/psych/visitors/yaml_tree.rb:544:in `each'
	12: from /usr/local/lib/ruby/2.6.0/psych/visitors/yaml_tree.rb:546:in `block in dump_ivars'
	11: from /usr/local/lib/ruby/2.6.0/psych/visitors/yaml_tree.rb:136:in `accept'
	10: from /usr/local/lib/ruby/2.6.0/psych/visitors/yaml_tree.rb:381:in `visit_Array'
	 9: from /usr/local/lib/ruby/2.6.0/psych/visitors/yaml_tree.rb:389:in `visit_Enumerator'
	 8: from /usr/local/lib/ruby/2.6.0/psych/visitors/yaml_tree.rb:389:in `each'
	 7: from /usr/local/lib/ruby/2.6.0/psych/visitors/yaml_tree.rb:389:in `block in visit_Enumerator'
	 6: from /usr/local/lib/ruby/2.6.0/psych/visitors/yaml_tree.rb:136:in `accept'
	 5: from /usr/local/lib/ruby/2.6.0/psych/visitors/yaml_tree.rb:163:in `visit_Object'
	 4: from /usr/local/lib/ruby/2.6.0/psych/visitors/yaml_tree.rb:544:in `dump_ivars'
	 3: from /usr/local/lib/ruby/2.6.0/psych/visitors/yaml_tree.rb:544:in `each'
	 2: from /usr/local/lib/ruby/2.6.0/psych/visitors/yaml_tree.rb:546:in `block in dump_ivars'
	 1: from /usr/local/lib/ruby/2.6.0/psych/visitors/yaml_tree.rb:136:in `accept'
/usr/local/lib/ruby/2.6.0/psych/visitors/yaml_tree.rb:298:in `visit_String': invalid byte sequence in UTF-8 (ArgumentError)
	6: from /vendor/bundle/ruby/2.6.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
	5: from /mains/homie/providers/manager.rb:60:in `block in call'
	4: from /mains/homie/providers/manager.rb:60:in `loop'
	3: from /mains/homie/providers/manager.rb:62:in `block (2 levels) in call'
	2: from /mains/homie/providers/manager.rb:125:in `router'
	1: from /mains/homie/providers/manager.rb:157:in `save_device_inventory'
/mains/homie/providers/manager.rb:161:in `rescue in save_device_inventory': undefined method `msg' for #<ArgumentError: invalid byte sequence in UTF-8> (NoMethodError)

```

**Comment by skoona** [comment]
Thanks for the trace.  The only way I know of to capture this errant char it to log everything running on your mqtt util this happens.  If you could send me that trace log ir would allow me/you to find this char.

$ mosquitto_sub -v -h <mqtt_host> -t homie/#  -u <userid> -P <passwd> > ~/tmp/skoona.log

James,
